# Project information
site_name: Roadmap
site_url: https://roadmap.schdesign.hu/
site_author: schdesign
site_description: >-
  A Simonyi Károly Szakkollégiumban működő schdesign öntevékeny kör
  szakmai anyagainak gyűjtőhelyéül szolgáló platform.

# Repository
repo_name: schdesign/roadmap
repo_url: https://git.sch.bme.hu/schdesign/roadmap
edit_uri: "" # "edit/master/docs/" # it would add and edit link at the top of all the articles

# Copyright
copyright: "" # "Copyright &copy; 2020 - 2022 schdesign"

# Configuration
theme: 
  name: material
  custom_dir: docs/theme
  # Static files
  static_templates:
    - 404.html
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true
  # Default values, taken from mkdocs_theme.yml
  features:
    - navigation.instant
    #- navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.indexes
  language: hu
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: img/favicon.png
  logo: img/schdesign_s_logo_white.svg
  icon:
    repo: fontawesome/brands/git-alt

# Extra files for past build customization
extra_javascript: 
  - extras/extra.js
  - extras/config.js
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css: 
  - extras/extra.css

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Customization
extra:
  #analytics:
  #  provider: google
  #  property: !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCrpoUHr-I8VjjLgXUz-AV6Q/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/schonherzdesignstudio/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/schdesign.hu/
    - icon: fontawesome/brands/behance
      link: https://www.behance.net/wearethesds/
    - icon: fontawesome/brands/gitlab
      link: https://git.sch.bme.hu/schdesign

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic:
      mode: view
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: schdesign
      repo: roadmap
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets:
      check_paths: true

# Page tree
nav:
  - Kezdőlap:
    - index.md
    - TODO: schdesign/todo.md
    - Design Principles: schdesign/workshop/2021-02-26.md
    - Markdown:
      - Alapok: schdesign/tutorial/markdown-alapok.md
      - Cheatsheet: schdesign/tutorial/markdown-cheatsheet.md
    - Hozzájárulás: schdesign/tutorial/hozzajarulas.md
    - Rólunk: schdesign/index.md
  - Web:
    - web/index.md
    - Első lépések: web/elso-lepesek.md
    - Workshopok: 
      - 2020/21/1 Todo lista: web/workshop/2020-21-1_todo-list.md
      - 2020/21/2 Web kezdő: web/workshop/2021-02-22.md
      - 2020/21/2 Web haladó: web/workshop/2021-03-03.md
    - Weboldal készítés az alapoktól:
      - 0. Bevezető: web/tutorial/step-by-step/index.md
      - 1. HTML: web/tutorial/step-by-step/html.md
      - 2. CSS: web/tutorial/step-by-step/css.md
      - 3. JS: web/tutorial/step-by-step/js.md
      - 4. Hova tovább: web/tutorial/step-by-step/hova-tovabb.md
  - Grafika:
    - grafika/index.md
    - Hasznos oldalak: grafika/grafika-hasznos.md
    - Workshopok: 
      - 2020/21/2 Photoshop kezdő: grafika/workshop/2021-02-24.md
      - 2020/21/2 Photoshop haladó: grafika/workshop/2021-03-01.md
      - 2020/21/2 Illustrator kezdő: grafika/workshop/2021-03-08.md
      - 2020/21/2 Illustrator haladó: grafika/workshop/2021-03-17.md
  - 3D:
    - 3d/index.md
    - Interfész bemutatása:
      - 1. rész: 3d/tutorial/interface/1.md
      - 2. rész: 3d/tutorial/interface/2.md
    - Denoising: 3d/tutorial/denoising/index.md
    - Workshopok: 
      - 2020/21/2 3D kezdő: 3d/workshop/2021-03-10.md
      - 2020/21/2 3D haladó: 3d/workshop/2021-03-15.md
